In [1]:
import pandas as pd
import glob

pd.set_option("display.max_rows", None)


manualColums = ['Background', 
                'Hair Style', 
                'Hair Color', 
                'Facial Hair', 
                'Top', 
                'Bottom',
                'Footwear',
                'Ring',
                'Headwear',
                'Glasses',
                'Piercings', 
                'Accessories']

In [2]:
#data_dictionary = pd.read_csv('Attributes_1_10000.csv',encoding = "utf-8")

df = pd.concat(map(pd.read_csv, glob.glob('./Attributes*.csv')))
print(len(df.index))

20000

In [3]:
for count in range(0, len(manualColums)):
    print(count)
    print(df[manualColums[count]].value_counts().to_frame())
    #print(df[manualColums[count]].value_counts(normalize=True).to_frame())
    print('---------------------------------')

0
       Background
White       19859
---------------------------------
1
                           Hair Style
Short Messy                      1978
None                             1967
Straight Sideswept Fringe        1953
Short Coil                       1830
Buzz Cut                         1818
Short Afro Fade                  1783
Medium Curly Bob                 1598
Low Ponytail                     1443
Short Pixie                      1386
Long Messy                       1314
Updo Bun                         1034
Short Updo                        943
Long Straight Bangs               425
Long Afro                         387
---------------------------------
2
             Hair Color
Black              5882
Light Brown        4405
Dark Brown         3640
Blonde             2793
Light Grey         1942
Auburn             1197
---------------------------------
3
          Facial Hair
None            14975
Stubble          1928
Thin             1008
Goatee            799
Mustache          777
Beard             372
---------------------------------
4
                                                     Top
Light Gray Longsleeve                               1377
Charcoal Blazer with Light Blue Shirt and No Tie    1241
Blue Longsleeve                                     1208
Navy Blazer with Striped Shirt and No Tie           1066
Navy Oxford with Buttons                             888
Charcoal Blazer with Light Blue Shirt and Black...   830
Dark Gray Longsleeve                                 787
Navy Blazer with Striped Shirt and Navy Tie          743
Gray Blazer with Black Shirt and No Tie              716
Olive Oxford with Buttons                            695
Navy Oxford with Pocket                              638
Navy Oxford with Tie                                 591
Red Longsleeve                                       584
Tan Blazer with Off-White Shirt and No Tie           516
Khaki Oxford with Buttons                            511
Olive Oxford with Pocket                             500
Olive Oxford with Tie                                495
Gray Blazer with Black Shirt and Gray Tie            447
Navy Oxford with Tie and Pocket                      369
Gray Oxford with Buttons                             369
Khaki Oxford with Tie                                354
Tan Blazer with Off-White Shirt and Tan Tie          352
Khaki Oxford with Pocket                             344
Navy Jumpsuit                                        338
Olive Oxford with Tie and Pocket                     329
Denim Jumpsuit                                       289
Gray Oxford with Pocket                              283
Gray Oxford with Tie                                 262
Gray Jumpsuit                                        209
Khaki Oxford with Tie and Pocket                     207
Gray Oxford with Tie and Pocket                      156
Khaki Jumpsuit                                       155
Light Gray Cardigan with Light Gray Longsleeve ...   136
Light Gray Cardigan with Beige Longsleeve Shirt      133
Dark Gray Cardigan with Light Gray Longsleeve S...   118
Dark Gray Cardigan with Beige Longsleeve Shirt       117
Light Gray Cardigan with Tan Longsleeve Shirt        103
Dark Gray Cardigan with Light Gray Oxford Shirt       96
Light Gray Cardigan with Light Gray Oxford Shirt      94
Light Gray Cardigan with Beige Oxford Shirt           93
Dark Gray Cardigan with Tan Longsleeve Shirt          93
Olive Cardigan with Light Gray Longsleeve Shirt       81
Light Gray Cardigan with Tan Oxford Shirt             79
Olive Cardigan with Beige Longsleeve Shirt            73
Brown Cardigan with Light Gray Longsleeve Shirt       65
Brown Cardigan with Beige Longsleeve Shirt            64
Olve Cardigan with Tan Longsleeve Shirt               60
Dark Gray Cardigan with Tan Oxford Shirt              60
Dark Gray Cardigan with Beige Oxford Shirt            58
Olive Cardigan with Light Gray Oxford Shirt           53
Brown Cardigan with Tan Longsleeve Shirt              53
Olive Cardigan with Beige Oxford Shirt                47
Olive Cardigan with Tan Oxford Shirt                  37
Dark Gray Cardigan with Off-White Longsleeve Shirt    37
Brown Cardigan with Tan Oxford Shirt                  35
Brown Cardigan with Light Gray Oxford Shirt           34
Dark Gray Cardigan with Off-White Oxford Shirt        31
Brown Cardigan with Beigse Oxford Shirt               30
Light Gray Cardigan with Off-White Oxford Shirt       30
Light Gray Cardigan with Off-White Longsleeve S...    29
Brown Cardigan with Off-White Longsleeve Shirt        23
Olive Cardigan with Off-White Longsleeve Shirt        18
Olive Cardigan with Off-White Oxford Shirt            16
Brown Cardigan with Off-White Oxford Shirt            14
---------------------------------
5
                  Bottom
Charcoal Slacks     4355
Navy Slacks         3667
Gray Slacks         2527
Dark-Wash Denim     2276
Light-Wash Denim    1948
Khaki Slacks        1841
Blue Denim          1298
None                 991
Khaki                956
---------------------------------
6
                                           Footwear
Brown Leather Shoes with Laces                 4201
White Canvas Sneaker with White Sole           3532
Black Suede Chelseas with Brown Sole           3039
Black Leather Shoes with Laces                 2684
Tan Suede Workboot with Tan Sole               2470
White Leather Sneaker with Grey Sole           2344
Redbrown Leather Workboot with Brown Sole      1585
Black Leather Chelsea with Blue Sole              4
---------------------------------
7
                Ring
None           16857
Two Rings       2808
Ring One Blue    194
---------------------------------
8
                       Headwear
None                      17801
Tan Workers Cap            1340
Navy Blue Workers Cap       525
Purple Workers Cap          193
---------------------------------
9
                   Glasses
None                 12892
Black Books           3957
Silver Aviators       1942
Rosegold Aviators     1061
Blue Books               6
3D Glasses               1
---------------------------------
10
              Piercings
None              17825
Stud Earring       2034
---------------------------------
11
                         Accessories
None                            6597
Black Smartphone                4361
Brown Leather Briefcase         3538
Black Leather Briefcase         2816
Lunchbox                        1938
Blue Lunchbox                    418
Light Blue Smartphone            191
---------------------------------